version: '3.1'
services:
  stats-server:
    build: statistic
    image: statistic
    container_name: statistic
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statsdb:5432/statsdb

  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-service:
    build: master
    image: master
    container_name: master
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
